name = "Romulusn_first_order"
description = "Romulus N with 1st order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/romulusae/romulus-hardware/tree/309c3861c04d1b91d3a946fee370945440d22196/romulusn/src_rtl/v1_1r_serld" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "../../LWC/LWC.toml", rtl.pos = 3 }, 
    "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]


[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/LWC_config2.v",
    "src_rtl/NIST_LWAPI_pkg.vhd",
	"src_rtl/api.v",
	"src_rtl/HPermutation.vhd",
	"src_rtl/key_reg.v",
	"src_rtl/key_reg_cg.v",
	"src_rtl/KeyExpansionNoReg.vhd",
	"src_rtl/lfsr_gf56.v",
	"src_rtl/lfsr2_20.v",
	"src_rtl/lfsr3_20.v",
	# "src_rtl/LWC_SCA.v",
	"src_rtl/mode_top.v",
	"src_rtl/Permutation.vhd",
	"src_rtl/pt4.v",
	"src_rtl/pt8.v",
	"src_rtl/RoundFunction_HPC2_ClockGating_d1.v",
	"src_rtl/SkinnyPKG.vhd",
	"src_rtl/state_reg.v",
	"src_rtl/state_reg_cg.v",
	"src_rtl/state_update_32b.v",
	"src_rtl/tkx_update_32b.v",
	"src_rtl/tky_update_32b.v",
	"src_rtl/tkz_update_32b.v",
	"src_rtl/tkz_update_32b_2.v",
]

top = "LWC_SCA"
# clock.port = "clk"
# reset.port = "rst"
# reset.active_high = true
# reset.asynchronous = false

[language]
vhdl.version = "2008"
verilog.version = "2001"

[tb]
sources = ["../../LWC/LWC_TB_SCA.vhd"]
top = "LWC_TB"
parameters.G_FNAME_PDI = {file = "KAT/pdi_shared_2.txt"}
parameters.G_FNAME_SDI = {file = "KAT/sdi_shared_2.txt"}
parameters.G_FNAME_DO = {file = "KAT/do.txt"}

[lwc.aead]
algorithm = "romulusn" #romulusn1v12
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = ["ad", "npub", "data"]
# input_sequence.decrypt = ["ad", "npub", "data", "tag"]

[lwc.ports]
pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 128
sdi.bit_width = 32
sdi.num_shares = 2

[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 1