name = "PHOTON-Beetle_second_order"
description = "PHOTON-Beetle with 2nd order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/GMUCERG/PHOTON-Beetle" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 2 },
    "../../gadgets.toml",
    # { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA_wrapper.toml", rtl.pos = -1 },
	{ uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]

[rtl]
sources = [
    "src_rtl/design_pkg.vhd",
    "src_rtl/LWC_config.vhd",
    "src_rtl/ctr.vhd",
    "src_rtl/ozs.vhd",
    "src_rtl/ozs2.vhd",
    "src_rtl/reg2.vhd",
    "src_rtl/rho.vhd",
    "src_rtl/datapath.vhd",
    "src_rtl/controller.vhd",
    "src_rtl/Photon_256_HPC2_ClockGating_d2.v",
	"src_rtl/CryptoCore_SCA.vhd",

	# "LWC/data_piso.vhd",
	# "LWC/data_sipo.vhd",
	# "LWC/FIFO.vhd",
	# "LWC/key_piso.vhd",
	# "LWC/LWC_SCA.vhd",
	# "LWC/NIST_LWAPI.vhd",
	# "LWC/PostProcessor.vhd",
	# "LWC/PreProcessor.vhd",
	# "HPC2/and_HPC2.vhd",
	# "HPC2/xnor_HPC2.vhd",
	# "HPC2/xor_HPC2.vhd",
	# "General/Mux2.vhd"
	# "General/mux2_masked.vhd"
	# "General/Gates.v"
	# "General/reg.vhd",
	# "General/xnor_2.vhd",
	# "General/xor_2.vhd",
]

# includes = []
top = "LWC_SCA_wrapper"
parameters.XW = 32
clock.port = "clk"

[language]
vhdl.version = "2008"
# vhdl.synopsys = false
verilog.version = "2001"

[tb]
# sources = ["LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_SCA_TB"

[lwc]
aead.algorithm = "photonbeetleaead128rate128v1"
block_size = {XT = 128, AD = 128, HM = 32}
hash.algorithm = "photonbeetlehash256rate32v1"

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 3
rdi.bit_width = 3360
# sdi.bit_width = 32
sdi.num_shares = 3
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 2