name = "SPARKLE_VT_h"
developer = "Virginia Tech"
description = "SCHWAEMM+ESCH"

dependencies = [
	{ uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_32.toml", rtl.pos = 1 },
]

[lwc]
aead.algorithm = "schwaemm256128v1"
aead.key_reuse = true
hash.algorithm = "esch256v1"
block_bits = { xt = 256, ad = 256, hm = 256 }

[language]
vhdl.version = "2008"
vhdl.synopsys = true

[rtl]
sources = [
    "src_rtl/v2/design_pkg.vhd",
    # "../LWC/hardware/LWC_rtl//NIST_LWAPI_pkg.vhd",
    "src_rtl/v2/utility_functions_pkg.vhd",
    "src_rtl/v2/SchwaemmEsch.vhd",
    "src_rtl/v2/SchwaemmEschController.vhd",
    "src_rtl/v2/CryptoCore.vhd",
]
# top = "LWC"
clock_port = "clk"


[tb.parameters]
G_TEST_MODE = 4
G_MAX_FAILURES = 0
G_FNAME_PDI.file = "../FAILING_KATS/pdi.txt"
G_FNAME_SDI.file = "../FAILING_KATS/sdi.txt"
G_FNAME_DO.file =  "../FAILING_KATS/do.txt"
