name = "GIFT-COFB_third_order"
description = "GIFT-COFB with 3rd order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/vtsal/gift_cofb_lwc_v2" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    # { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 2 },
    # "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]


[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/design_pkg.vhd",
    "../../LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/ConsGen.vhd",
    "src_rtl/SomeFunc.vhd",
    "src_rtl/GIFT128.vhd",
    "src_rtl/myReg.vhd",
    "src_rtl/PermBits.vhd",
    "../../HPC2/and_HPC2.vhd",
    "../../HPC2/xnor_HPC2.vhd",
    "../../HPC2/xor_HPC2.vhd",
    "../../General/my_register.vhd",
    "../../General/xnor_2.vhd",
    "../../General/xor_2.vhd",
    "src_rtl/GIFTCOFB_Controller.vhd",
    "src_rtl/SubCells_HPC2_ClockGating_d3.v",
    "src_rtl/GIFTCOFB_Datapath.vhd",
    "src_rtl/GIFTCOFB.vhd",
    "src_rtl/CryptoCore_SCA.vhd",

    "../../LWC/old/PreProcessor.vhd",

    "../../LWC/SIPO.vhd",
    "../../LWC/PostProcessor.vhd",
    "../../LWC/FIFO.vhd",
    "../../LWC/LWC_SCA.vhd",
]

# [rtl]
# sources = [
# 	"src_rtl/ConsGen.vhd",
# 	"src_rtl/CryptoCore_SCA.vhd",
# 	"src_rtl/design_pkg.vhd",
# 	"src_rtl/GIFT128.vhd",
# 	"src_rtl/GIFTCOFB.vhd",
# 	"src_rtl/GIFTCOFB_Controller.vhd",
# 	"src_rtl/GIFTCOFB_Datapath.vhd",
# 	"src_rtl/LWC_config.vhd",
# 	"src_rtl/myReg.vhd",
# 	"src_rtl/PermBits.vhd",
# 	"src_rtl/SomeFunc.vhd",
# 	"src_rtl/SubCells_HPC2_ClockGating_d3.v",
# 	"LWC/data_piso.vhd",
# 	"LWC/data_sipo.vhd",
# 	"LWC/FIFO.vhd",
# 	"LWC/key_piso.vhd",
# 	"LWC/LWC_SCA.vhd",
# 	"LWC/NIST_LWAPI.vhd",
# 	"LWC/PostProcessor.vhd",
# 	"LWC/PreProcessor.vhd",
# 	"HPC2/and_HPC2.vhd",
# 	"HPC2/xnor_HPC2.vhd",
# 	"HPC2/xor_HPC2.vhd",
# 	"General/reg.vhd",
# 	"General/xnor_2.vhd",
# 	"General/xor_2.vhd",
# ]

# includes = []
top = "LWC_SCA_wrapper"
clock.port = "clk"
# clock.port = "clk"
# reset.port = "rst"
# reset.active_high = true
# reset.asynchronous = false
# parameters = { G_DO_FIFO_DEPTH = 1 }
[language]
vhdl.version = "2008"
# vhdl.synopsys = false
verilog.version = "2001"
# systemverilog.version = "2009"
# [tb]
# sources = ["LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_SCA_TB"
[lwc]
block_bits = { AD = 128, XT = 128}
aead.algorithm = "giftcofb128v1"
# aead.key_reuse = true
aead.input_sequence.encrypt = ['npub', 'ad', 'pt']
aead.input_sequence.decrypt = ['npub', 'ad', 'ct', 'tag']
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = ["npub", "ad", "pt"]
# input_sequence.decrypt = ["npub", "ad", "ct", "tag"]
# [lwc.hash]
# algorithm = "" ###### (hashing is not supported)
# digest_bits = 0
[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 4
rdi.bit_width = 1152
# sdi.bit_width = 32
sdi.num_shares = 4
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 3

[tb]
sources = ["../../LWC/LWC_TB_SCA.vhd"]
top = "LWC_TB"
parameters.G_FNAME_PDI = {file = "KAT/pdi_shared_4.txt"}
parameters.G_FNAME_SDI = {file = "KAT/sdi_shared_4.txt"}
parameters.G_FNAME_DO = {file = "KAT/do.txt"}
# parameters.G_FNAME_PDI = {file = "BENCH_KAT/GIFT-COFB_first_order/timing_tests/pdi_shared_2.txt"}
# parameters.G_FNAME_SDI = {file = "BENCH_KAT/GIFT-COFB_first_order/timing_tests/sdi_shared_2.txt"}
# parameters.G_FNAME_DO = {file =  "BENCH_KAT/GIFT-COFB_first_order/timing_tests/do.txt"}
parameters.G_TEST_MODE = 4