name = "Isapa_first_order"
description = "Isapa with 1st order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/romulusae/romulus-hardware/tree/309c3861c04d1b91d3a946fee370945440d22196/romulusn/src_rtl/v1_1r_serld" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA_2Pass.toml", rtl.pos = 2 },
    # { uri = "/nhome/mmohajer/src/LWC-Masking/.xeda_dependencies/github.com/GMUCERG/LWC.git/hardware/LWC_SCA_2Pass.toml", rtl.pos = 2 },
    # "../../gadgets.toml",
    # { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]

[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/design_pkg.vhd",
    # "src_rtl/NIST_LWAPI_pkg.vhd",
    # "src_rtl/StepDownCountLd.vhd",
    # "src_rtl/PreProcessor.vhd",
    # "src_rtl/PostProcessor.vhd",
    # "src_rtl/StepDownCountLd.vhd",
    # "src_rtl/FIFO.vhd",
    "../../HPC2/and_HPC2.vhd",
    "../../HPC2/nor_HPC2.vhd",
    "../../HPC2/xnor_HPC2.vhd",
    "../../HPC2/xor_HPC2.vhd",
    "../../General/Gates.vhd",
    "../../General/not_masked.vhd",
    "../../General/my_register.vhd",
    "../../General/xnor_2.vhd",
    "../../General/xor_2.vhd",
    "src_rtl/isap_pkg.vhd",
    "src_rtl/Asconp_HPC2_ClockGating_d1.v",
    "src_rtl/CryptoCore_SCA_2pass.vhd",
    # "src_rtl/LWC_SCA_2Pass.vhd",
]

top = "LWC_SCA"
# clock.port = "clk"
# reset.port = "rst"
# reset.active_high = true
# reset.asynchronous = false
# [tb]
# sources = [ # 
#     "src_tb/LWC_TB_SCA.vhd",
# ]
# top = "LWC_TB"

[tb.generics]
G_FNAME_PDI.file = "KAT/pdi_shared_2.txt"
G_FNAME_SDI.file = "KAT/sdi_shared_2.txt"
G_FNAME_DO.file = "KAT/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 10_000
G_RANDOM_SEED = 1
G_PDI_STALLS = 7
G_SDI_STALLS = 13
G_DO_STALLS = 21
G_RANDOM_STALL = true                     # true


[language]
vhdl.version = "2008"
verilog.version = "2001"

[lwc]
aead.algorithm = "isapa128av20"
aead.key_reuse = true
aead.input_sequence.encrypt = ['npub', 'pt', 'ad', 'tag']
aead.input_sequence.decrypt = ['npub', 'ad', 'ct', 'tag']
hash.algorithm = "asconhashv12"

ports.pdi.bit_width = 32
ports.sdi.bit_width = 32
ports.pdi.num_shares = 2
ports.sdi.num_shares = 2

[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 1
