name = "SPARKLE_first_order"
description = "SPARKLE with 1st order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/vtsal/schwaemm_esch_lwc_aead_hash" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    # { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 2 },
    "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]

[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/design_pkg.vhd",
    "../../LWC/NIST_LWAPI_pkg.vhd",

    # "../../HPC2/and_HPC2.vhd",
    # "../../HPC2/xor_HPC2.vhd",
    # "../../General/Mux2.vhd",
    # "../../General/mux2_masked.vhd",
    # "../../General/reg.vhd",
    # "../../General/xor_2.vhd",
    "src_rtl/arx_round_HPC2_ClockGating_d1.v",
    "src_rtl/utility_functions_pkg.vhd",
    "src_rtl/SchwaemmEsch.vhd",
    "src_rtl/SchwaemmEschController.vhd",
    "src_rtl/CryptoCore_SCA.vhd",

    "../../LWC/old/PreProcessor.vhd",

    "../../LWC/SIPO.vhd",
    "../../LWC/PostProcessor.vhd",
    "../../LWC/FIFO.vhd",
    "../../LWC/LWC_SCA.vhd",
]

# top = "LWC_SCA"
# clock.port = "clk"

[tb]
sources = ["../../LWC/LWC_TB_SCA.vhd"]
top = "LWC_TB"

# [tb.parameters]
# G_TEST_MODE = 4
# G_MAX_FAILURES = 0
# G_FNAME_PDI.file = "FAILED_KATS/pdi_shared_2.txt"
# G_FNAME_SDI.file = "FAILED_KATS/sdi_shared_2.txt"
# G_FNAME_DO.file = "FAILED_KATS/do.txt"

[language]
vhdl.version = "2008"
vhdl.synopsys = true
verilog.version = "2001"

[lwc]
block_bits = { AD = 256, XT = 256, HM = 128 }
aead.algorithm = "schwaemm256128v1"
hash.algorithm = "esch256v1"

[lwc.ports]
pdi.bit_width = 32
pdi.num_shares = 2
sdi.bit_width = 32
sdi.num_shares = 2
rdi.bit_width = 1536
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 1
