name = "Elephant_second_order"
description = "Elephant with 2nd order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/GMUCERG/Elephant/tree/master/src_rtl/v1" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 3 },
    "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]


[rtl]
sources = [
    "src_rtl/elephant_constants.vhd",
    "src_rtl/design_pkg.vhd",
    "src_rtl/LWC_config.vhd",
    "../../LWC/NIST_LWAPI_pkg.vhd",

    "src_rtl/elephant_datapath_lfsr.vhd",
    "src_rtl/elephant_datapath.vhd",

    "src_rtl/elephant_perm_HPC2_ClockGating_d2.v",
    "src_rtl/elephant_perm_lfsr.vhd",
    "src_rtl/CryptoCore_SCA.vhd",

    # "LWC/data_piso.vhd",
    # "LWC/data_sipo.vhd",
    # "LWC/FIFO.vhd",
    # "LWC/key_piso.vhd",
    # "LWC/LWC_SCA.vhd",
    # "LWC/NIST_LWAPI.vhd",
    # "LWC/PostProcessor.vhd",
    # "LWC/PreProcessor.vhd",
    # "HPC2/and_HPC2.vhd",
    # "HPC2/xnor_HPC2.vhd",
    # "HPC2/xor_HPC2.vhd",
    # "General/not_masked.v",
    # "General/reg.vhd",
    # "General/xnor_2.vhd",
    # "General/xor_2.vhd",
    "../../LWC/old/PreProcessor.vhd",

    "../../LWC/SIPO.vhd",
    "../../LWC/PostProcessor.vhd",
    "../../LWC/FIFO.vhd",
    "../../LWC/LWC_SCA.vhd",
]
top = "LWC_SCA_wrapper"
clock.port = "clk"
parameters.XW = 32

[tb]
sources = ["../../LWC/LWC_TB_SCA.vhd"]
top = "LWC_TB"
parameters.G_FNAME_PDI = { file = "KAT/pdi_shared_3.txt" }
parameters.G_FNAME_SDI = { file = "KAT/sdi_shared_3.txt" }
parameters.G_FNAME_DO = { file = "KAT/do.txt" }
parameters.G_TEST_MODE = 4
parameters.G_MAX_FAILURES = 100


[language]
vhdl.version = "2008"
# vhdl.synopsys = false
verilog.version = "2001"

[lwc]
aead.algorithm = "elephant160v1"
block_bits = { AD = 160, PT = 160 }

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 3
rdi.bit_width = 840
# sdi.bit_width = 32
sdi.num_shares = 3
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 2
