name = "Xoodyak_R3_first_order"
description = "Xoodyak R3 with 1st order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/KeccakTeam/Xoodoo/tree/master/Hardware/FPGA/AEADandHashing/Xoodyak_R3" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 2 }, 
    "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]

[rtl]
sources = [
	"src_rtl/design_pkg.vhd",
	"src_rtl/LWC_config.vhd",
	"src_rtl/xoodoo_globals.vhd",
	"src_rtl/xoodoo_rc.vhd",
	"src_rtl/xoodoo.vhd",
	"src_rtl/xoodoo_register.vhd",
	"src_rtl/xoodoo_round_HPC2_ClockGating_d1.v",
	"src_rtl/xoodoo_n_rounds.vhd",
	"src_rtl/CryptoCore_SCA.vhd",
	# "LWC/data_piso.vhd",
	# "LWC/data_sipo.vhd",
	# "LWC/FIFO.vhd",
	# "LWC/key_piso.vhd",
	# "LWC/LWC_SCA.vhd",
	# "LWC/NIST_LWAPI.vhd",
	# "LWC/PostProcessor.vhd",
	# "LWC/PreProcessor.vhd",
	# "HPC2/nand_HPC2.vhd",
	# "HPC2/nor_HPC2.vhd",
	# "HPC2/xnor_HPC2.vhd",
	# "HPC2/xor_HPC2.vhd",
	# "General/not_masked.vhd",
	# "General/reg.vhd",
	# "General/xnor_2.vhd",
	# "General/xor_2.vhd",
]

# includes = []
top = "LWC_SCA"
# clock.port = "clk"
# reset.port = "rst"
# reset.active_high = true
# reset.asynchronous = false
# parameters = { G_DO_FIFO_DEPTH = 1 }
[language]
vhdl.version = "2008"
# vhdl.synopsys = false
verilog.version = "2001"
# systemverilog.version = "2009"
# [tb]
# sources = ["LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_SCA_TB"
[lwc.aead]
algorithm = "xoodyakround3"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = ["npub", "ad", "data"]
# input_sequence.decrypt = ["npub", "ad", "data", "tag"]
[lwc.hash]
algorithm = "xoodyakround3"
# digest_bits = 128
[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 384
# sdi.bit_width = 32
sdi.num_shares = 2
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 1

[lwc.block_bits]
xt = 192
ad = 352
hm = 128

# [tb]
# sources = ["../../LWC/LWC_TB_SCA.vhd"]
# top = "LWC_TB"
# parameters.G_FNAME_PDI = {file = "KAT/pdi_shared_2.txt"}
# parameters.G_FNAME_SDI = {file = "KAT/sdi_shared_2.txt"}
# parameters.G_FNAME_DO =  {file = "KAT/do.txt"}
