name = "Ascon128v12_first_order"
description = "Ascon128v12 with 1st order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/ascon/ascon-hardware/tree/master/src_rtl/v1" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    # { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA.toml", rtl.pos = 3 },
    "../../gadgets.toml",
    { uri = "../../LWC/wrapper.toml", rtl.pos = -1 },
]


[rtl]
sources = [
    "src_rtl/design_pkg.vhd",
    "src_rtl/LWC_config.vhd",
    "../../LWC/NIST_LWAPI_pkg.vhd",
    "src_rtl/ascon_pkg.vhd",
    "../../LWC/SIPO.vhd",
    "../../LWC/PISO.vhd",
    "../../LWC/FIFO.vhd",
    "../../LWC/PostProcessor.vhd",
    "../../LWC/PreProcessor.vhd",
    # "../../HPC2/and_HPC2.vhd",
    # "../../HPC2/xnor_HPC2.vhd",
    # "../../HPC2/xor_HPC2.vhd",
    # "../../General/Gates.vhd",
    # "../../General/not_masked.vhd",
    # "../../General/my_register.vhd",
    # "../../General/xnor_2.vhd",
    # "../../General/xor_2.vhd",
    "src_rtl/Asconp_HPC2_ClockGating_d1.v",
    "src_rtl/CryptoCore_SCA.vhd",
    "../../LWC/LWC_SCA.vhd",
]

parameters.XW = 32

# includes = []
top = "LWC_SCA_wrapper"
# clock.port = "clk"
# reset.port = "rst"
# reset.active_high = true
# reset.asynchronous = false
[language]
vhdl.version = "2008"
# vhdl.synopsys = false
verilog.version = "2001"
# systemverilog.version = "2009"
# [tb]
# sources = ["LWC_SCA_TB.vhd"]
# includes = []
# top = "LWC_SCA_TB"
[lwc]
block_bits = { AD = 64, XT = 64}
aead.algorithm = "ascon128v12"
aead.key_reuse = true
hash.algorithm = "asconhashv12"

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 320
# sdi.bit_width = 32
sdi.num_shares = 2
[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 1


[tb]
# sources = ["../../LWC/LWC_TB_SCA.vhd"]
# top = "LWC_TB"
parameters.G_FNAME_PDI = {file = "KAT/pdi_shared_2.txt"}
parameters.G_FNAME_SDI = {file = "KAT/sdi_shared_2.txt"}
parameters.G_FNAME_DO = {file = "KAT/do.txt"}


[flows.vivado_synth]
fpga.part = "xc7a100tftg256-2L"
synth.strategy =  "Flow_AlternateRoutability"
# impl.strategy = "Performance_ExtraTimingOpt"
clock_period = 10.0

[flows.vivado_alt_synth]
fpga.part = "xc7a100tftg256-2L"
synth.strategy = "ExtraTimingCongestion"
impl.strategy = "ExtraTimingCongestion"
clock_period = 10.0