name = "Isapa_third_order"
description = "Isapa with 3rd order masking"
author = ["Nicolai Mueller", "Amir Moradi"]
url = "https://github.com/romulusae/romulus-hardware/tree/309c3861c04d1b91d3a946fee370945440d22196/romulusn/src_rtl/v1_1r_serld" # Reference design which we protect
license = "GPL-3.0"
version = "0.1.0"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA_2Pass.toml", rtl.pos = 2 },
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_SCA_wrapper.toml", rtl.pos = -1 },
]

[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/design_pkg.vhd",
    "../../HPC2/and_HPC2.vhd",
    "../../HPC2/nor_HPC2.vhd",
    "../../HPC2/xnor_HPC2.vhd",
    "../../HPC2/xor_HPC2.vhd",
    "../../General/Gates.vhd",
    "../../General/not_masked.vhd",
    "../../General/my_register.vhd",
    "../../General/xnor_2.vhd",
    "../../General/xor_2.vhd",
    "src_rtl/isap_pkg.vhd",
    "src_rtl/Asconp_HPC2_ClockGating_d3.v",
    "src_rtl/CryptoCore_SCA_2pass.vhd",
]

# top = "LWC_SCA_wrapper"
# parameters.XW = 32
# clock.port = "clk"

[tb]
sources = [ # 
    "../../LWC/LWC_TB_SCA.vhd",
]
top = "LWC_TB"
generics.G_FNAME_PDI.file = "KAT/pdi_shared_4.txt"
generics.G_FNAME_SDI.file = "KAT/sdi_shared_4.txt"
generics.G_FNAME_DO.file = "KAT/do.txt"
generics.G_TIMEOUT_CYCLES = 100_000

[language]
vhdl.version = "2008"
verilog.version = "2001"

[lwc]
block_bits = { AD = 64, XT = 64 }
aead.algorithm = "isapa128av20"
# aead.key_reuse = true
aead.input_sequence.encrypt = ['npub', 'pt', 'ad', 'tag']
aead.input_sequence.decrypt = ['npub', 'ad', 'ct', 'tag']
hash.algorithm = "asconhashv12"

[lwc.ports]
pdi.width = 32
pdi.shares = 4
sdi.width = 32
sdi.shares = 4
rdi.bit_width = 1920

[lwc.sca_protection]
target = ["spa", "dpa", "cpa", "timing"]
order = 3